/*created time 2016-4-21
  @auther xiaoling 
 **/


package CreditLine



import com.madai.model.approval.CreditLine.CreditLineIn;
import com.madai.model.approval.CreditLine.CreditLineOut;
//list any import classes here.


//declare any global variables here
rule"ESTBase_Line_EST00045"
    ruleflow-group "ESTDsrMore75AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0013");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00045"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00046"
    ruleflow-group "ESTDsrMore75AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0014");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00046"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00047"
    ruleflow-group "ESTDsrMore75AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0015");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00047");  
        update(cOut);    
end
rule"ESTBase_Line_EST00048"
    ruleflow-group "ESTDsrMore75AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0016");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00048");   
        update(cOut);   
end