/*created time 2016-4-21
  @auther xiaoling 
 **/


package CreditLine



import com.madai.model.approval.CreditLine.CreditLineIn;
import com.madai.model.approval.CreditLine.CreditLineOut;
//list any import classes here.


//declare any global variables here
rule"ESTBase_Line_EST00017"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0001");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00017"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00018"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0002");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00018"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00019"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0003");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00019"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00020"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0004");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00020"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00021"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0005");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00021"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00022"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0006");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00022"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00023"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0007");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00023"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00024"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0008");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00024");  
        update(cOut);    
end
rule"ESTBase_Line_EST00025"
    ruleflow-group "ESTDsrMore100AndLess5"  
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0009");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00025");
        update(cOut);      
end
rule"ESTBase_Line_EST00026"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0010");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00026"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00027"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0011");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00027");  
        update(cOut);    
end
rule"ESTBase_Line_EST00028"
    ruleflow-group "ESTDsrMore100AndLess5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0012");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00028");   
        update(cOut);   
end
