/*created time 2016-4-21
  @auther xiaoling 
 **/


package CreditLine



import com.madai.model.approval.CreditLine.CreditLineIn;
import com.madai.model.approval.CreditLine.CreditLineOut;
//list any import classes here.


//declare any global variables here
rule"ESTBase_Line_EST00033"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0001");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00033");   
        update(cOut);   
end
rule"ESTBase_Line_EST00034"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0002");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00034"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00035"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0003");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00035");  
        update(cOut);    
end
rule"ESTBase_Line_EST00036"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0004");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00036");   
        update(cOut);   
end
rule"ESTBase_Line_EST00037"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0005");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00037"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00038"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0006");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00038");  
        update(cOut);    
end
rule"ESTBase_Line_EST00039"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0007");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00039");  
        update(cOut);    
end
rule"ESTBase_Line_EST00040"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0008");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00040");  
        update(cOut);    
end
rule"ESTBase_Line_EST00041"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0009");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00041"); 
        update(cOut);     
end
rule"ESTBase_Line_EST00042"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0010");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00042");   
        update(cOut);   
end
rule"ESTBase_Line_EST00043"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0011");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00043");   
        update(cOut);   
end
rule"ESTBase_Line_EST00044"
    ruleflow-group "ESTDsrMore100AndMore5"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EST_0012");
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(-1);
        cOut.setAmount(cExt.getBase()*(-1));
        cOut.setReturnCode("Line_EST00044"); 
        update(cOut);     
end