/*created time 2016-4-22
  @auther xiaoling 
 **/


package CreditLine



import com.madai.model.approval.CreditLine.CreditLineIn;
import com.madai.model.approval.CreditLine.CreditLineOut;
//list any import classes here.


//declare any global variables here

rule "EWTBase_Line_EWT00152"

    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0004" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00152");   
        update(cOut);   
end

rule "EWTBase_Line_EWT00083"

    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0005" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00083"); 
        update(cOut);     
end

rule "EWTBase_Line_EWT00084"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0006" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00084"); 
        update(cOut);     
end

rule "EWTBase_Line_EWT00085"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0007" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00085"); 
        update(cOut);     
end

rule "EWTBase_Line_EWT00086"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0008" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00086");  
        update(cOut);    
end

rule "EWTBase_Line_EWT00087"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0009" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00087"); 
        update(cOut);     
end

rule "EWTBase_Line_EWT00088"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0010" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00088"); 
        update(cOut);     
end

rule "EWTBase_Line_EWT00089"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0011" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00089");  
        update(cOut);    
end

rule "EWTBase_Line_EWT00090"
    ruleflow-group "EWTDsrLessThrAndSalaryMoreAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0012" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00090");  
        update(cOut);    
end