/*created time 2016-4-22
  @auther xiaoling 
 **/


package CreditLine



import com.madai.model.approval.CreditLine.CreditLineIn;
import com.madai.model.approval.CreditLine.CreditLineOut;
//list any import classes here.


//declare any global variables here


rule "EWTBase_Line_EWT00136"

    ruleflow-group "EWTDsrLessOneAndSalaryNaAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0013" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00136");  
        update(cOut);    
end

rule "EWTBase_Line_EWT00137"

    ruleflow-group "EWTDsrLessOneAndSalaryNaAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0014" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00137"); 
        update(cOut);     
end

rule "EWTBase_Line_EWT00138"

    ruleflow-group "EWTDsrLessOneAndSalaryNaAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0015" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00138");  
        update(cOut);    
end

rule "EWTBase_Line_EWT00139"

    ruleflow-group "EWTDsrLessOneAndSalaryNaAndLess"
    no-loop true
    when
        //conditions
         cExt:CreditLineIn(middleCode=="EWT_0016" );
         cOut:CreditLineOut();  
    then
        //actions
        cOut.setAppId(cExt.getAppId());
        cOut.setProductCode(cExt.getProductCode());
        cOut.setTimes(cOut.getTimes());
        cOut.setAmount(cExt.getIncome()*cOut.getTimes());
        cOut.setReturnCode("Line_EWT00139"); 
        update(cOut);     
end