//created on: 2016-3-18
package autoAuditOneCreditScore


import com.madai.model.approval.CreditScoreAutoAuditOneOut;
import com.madai.model.approval.CreditScoreAutoAuditOneExtendIn;
import java.lang.Math;
import java.math.BigDecimal;
//list any import classes here.



//declare any global variables here




rule "DefaultGroupAndeLevel"

          ruleflow-group "modelThrDefault"
    when
        //conditions
         cOut:CreditScoreAutoAuditOneOut();
         cExt:CreditScoreAutoAuditOneExtendIn();
    then
        //actions
        cOut.setGroupLevel("C");
        cOut.setRiskLevel("中");
        cOut.setScore(0);
        cOut.setAppId(cExt.getAppId());
        cOut.setModelVersion("1.0.0");
end

