//created on: 2016-3-18
package autoAuditOneCreditScore


import com.madai.model.approval.CreditScoreAutoAuditOneOut;
import com.madai.model.approval.CreditScoreAutoAuditOneExtendIn;
import java.lang.Math;
import java.math.BigDecimal;
//list any import classes here.



//declare any global variables here




rule "modelOneCreditScore"
          ruleflow-group "modelOneCreditScore"
          no-loop true
    when
        //conditions
         cOut:CreditScoreAutoAuditOneOut();
         cExt:CreditScoreAutoAuditOneExtendIn();
    then
        //actions    
        double a_0=-3.2245;
        double a_1=cExt.getSex_1();
        double a_2=cExt.getDegree_1();
        double a_3=cExt.getHouse_2();
        double a_4=cExt.getArea_1();
        double a_5=cExt.getCitycategory_1();
        double a_6=cExt.getS2yquery_sqrt();
        double a_7=cExt.getS3mquery();
        double a_8=cExt.getM24_ccap_reject_cn_2();
        double a_9=cExt.getWork_time_1();
        double a_10=cExt.getCc_1st_open_intvl();
        double a_11=cExt.getCc_overdraw_rate_r_1();
        double a_12=cExt.getCc_overdraw_rate_r_2();
        double a_13=cExt.getLn_1st_open_intvl_1();
        double a_14=cExt.getCc_mean_line_rmb_2(); 
        double a_15=cExt.getCc_num_fc(); 
        
        //System.out.println("model_one");
        //System.out.println("a_1:"+a_1);
        //System.out.println("a_2:"+a_2);
        //System.out.println("a_3:"+a_3);
        //System.out.println("a_4:"+a_4);
        //System.out.println("a_5:"+a_5);
        //System.out.println("a_6:"+a_6);
        //System.out.println("a_7:"+a_7);
        //System.out.println("a_8:"+a_8);
        //System.out.println("a_9:"+a_9);
        //System.out.println("a_10:"+a_10);
        //System.out.println("a_11:"+a_11);
        //System.out.println("a_12:"+a_12);
        //System.out.println("a_13:"+a_13);
        //System.out.println("a_14:"+a_14);
        //System.out.println("a_15:"+a_15);
        
        double k_1=0.6711;
        double k_2=-0.3489;
        double k_3=-0.2127;
        double k_4=0.2478;
        double k_5=0.2387;
        double k_6=0.1702;
        double k_7=0.0568;
        double k_8=0.2263;
        double k_9=0.3246;
        double k_10=-0.0108;
        double k_11=0.2956;
        double k_12=0.6125;
        double k_13=0.2517;
        double k_14=-0.1949;
        double k_15=-0.127;
             
        double k=a_0+a_1*k_1+a_2*k_2+a_3*k_3+a_4*k_4+a_5*k_5+a_6*k_6+a_7*k_7+a_8*k_8+a_9*k_9+a_10*k_10+a_11*k_11+a_12*k_12+a_13*k_13+a_14*k_14+a_15*k_15;
        cOut.setScore(1/(1+Math.exp(-k)));
        
        System.out.println("modelone_cOut.setScore:"+cOut.getScore());
        
        update(cOut);
end

